### ISSUE TITLE
hmmtree options still part of mpt_options()

### ISSUE THREAD

**Issue by singmann** [mpt-network/MPTmultiverse#10]
One can still find `hmmtree` options in the `mpt_options()`:

```
$hmmtree
$hmmtree$n.optim
[1] 2

$hmmtree$max_classes
[1] 3

$hmmtree$fisher_information
[1] "expected"
```

These options should probably not be added when `HMMtree` is not there.
@mariusbarth

**Comment by mariusbarth** [comment]
Sure.
