### ISSUE TITLE
Used options in output object

### ISSUE THREAD

**Issue by mariusbarth** [mpt-network/MPTmultiverse#12]
Should we store the used options in the output object? I think this would be wise, and column `estimation` seems a good location for this information, to me. Could do that.

**Comment by danheck** [comment]
Yes, this sounds very reasonable and useful. Moreover, it will not take much space when stored as a list-column. Only one minor question: Maybe the column label `options` better describes the content?

**Comment by mariusbarth** [comment]
You're right -- I had sth in mind like nesting within `estimation` (where we currently store computation times), but that doesn't make any sense (because the observation unit is each estimated model, not each estimation method). So I also think an additional, top-level column for options is a better choice (here, the observation unit is each estimation method).
