### ISSUE TITLE
Consistency of output

### ISSUE THREAD

**Issue by mariusbarth** [mpt-network/MPTmultiverse#13]
Hey guys,

while inspecting the results object, I figured out that the data types of some columns are handled inconsistently (e.g., `condition` may be either character or factor, similar issues arise with `id` or `parameter`). I think to make the code more solid and testable, we should agree on how to store these columns.

Here's my suggestion: all of these should be character. I think this is the most convenient way, we don't have to carry around possible factor levels, and it's my impression that efficiency considerations (that would lead me to use factors or integers) are not a concern, yet.

**Comment by danheck** [comment]
I agree that consistently using character values makes a lot of sense. The only benefit of factors are the ordering of the factor levels when plotting the results for a specific model. Since this is of minor importance, we can just use characters.

**Comment by mariusbarth** [comment]
I think everything is consistent, now.
