### ISSUE TITLE
Across-participant correlations (latent-trait)

### ISSUE THREAD

**Issue by danheck** [mpt-network/MPTmultiverse#17]
We need to store the estimated correlation matrix `rho` for the latent-trait model to assess "how dependencies across participants can affect parameter agreement".

**Comment by danheck** [comment]
We will store this information in a new column `est_rho`

**Comment by singmann** [comment]
Is adding a new column that only holds information from a single estimation method really a good idea? Seems a little excessive to me.

Maybe we could instead add a column like `extra` that holds a list or so of such additional information which we only compute for certain methods (i.e., that could also hold the `fungibility` information, #18)

**Comment by danheck** [comment]
This is now implemented in 1009368e91f454a38a3f63631b0f17a42467e9a3.

As discussed today, I've added new columns for `est_rho`and  `fungibility` to allow for easier unnesting. In principle, these columns could also be filled by other methods (e.g., using the Fisher information matrix in ML estimation).
