### ISSUE TITLE
Improvements to `fit_mpt()`

### ISSUE THREAD

**Issue by mariusbarth** [mpt-network/MPTmultiverse#2]
After our meeting, it is clear that `fit_mpt()` needs some more features:

- [x] Ability to select/deselect all available methods.
- [x] Add a parameter to provide information which parameters are core and which parameters are auxiliary/nuisance.
- [x] Track the time that was needed for each individual model.

**Comment by singmann** [comment]
I would like to discuss the argument order in `fit_mpt`. Currently, the first argument, `method` is optional, but the following arguments are not optional. This means one either has to use argument names or always specify `method` although it is optional. I suggest to place `method` either behind the actually necessary arguments (i.e., after `model`) or as the last argument.

**Comment by mariusbarth** [comment]
I think everything discussed here is done.
