### ISSUE TITLE
Check results: Distinguish auxiliary vs. core parameters

### ISSUE THREAD

**Issue by danheck** [mpt-network/MPTmultiverse#21]
In the preregistration we require convergence of the core parameters, whereas auxiliary parameters are less important. Currently, we do not distinguish this in the check functions `check_results` and `write_check_results`.

Edit: The `check_results` output regarding the Bayesian approaches uses cryptic parameter names. This is hardly informative.

**Comment by singmann** [comment]
`MPTinR` checks via `check_fit()` now separate between core and non-core parameters (added in 52d68db7580623fa2fb909548ebde145fce79803).

Do we feel this is enough to close this issue?

**Comment by mariusbarth** [comment]
I think we should keep it open as a reminder that this is not implemented for the Bayesian approaches.
