### ISSUE TITLE
Calculation of CIs for no-pooling models

### ISSUE THREAD

**Issue by mariusbarth** [mpt-network/MPTmultiverse#3]
Confidence intervals for the no-pooling-models should be calculated in a more comparable way.

**Comment by mariusbarth** [comment]
Hi @singmann,
in `mptinr.R`, can you have a look at lines 210-246? There, the CIs for the no-pooling approaches are calculated. From my reading of the code, I have the impression that the "CIs" are the quantiles of the distribution of individual parameter estimates, but I'm not 100% sure. As far as I understood, we wanted to calculate CIs similar to se, i.e. just take `qnorm(p = .025, mean = est, sd = se)`. Or am I completely mistaken here?

**Comment by singmann** [comment]
I have changed this in the code now. The one problem is that CIs can now be larger than 1 or smaller than 0. I think this is just a logical consequence of calculating them based on estimate + x*SE. But I am happy to discuss this. Therefore, I leave the issue open.

**Comment by mariusbarth** [comment]
I think CIs exceeding the range of [0, 1] are not problematic, as this is what can also happen with the CIs from complete-pooling models.

**Comment by danheck** [comment]
I agree that this is not a problem for the current project, especially since we are mainly interested in the SE of the mean parameter.

**Comment by singmann** [comment]
Ok, I will close this issue then.
