### ISSUE TITLE
Use C++ implementation of beta-MPT

### ISSUE THREAD

**Issue by mariusbarth** [mpt-network/MPTmultiverse#7]
I don't know if I remember correctly: Should we use the C++ version of beta-MPT as a default?

**Comment by danheck** [comment]
In the first tests of the script, the `betaMPTcpp` (C++) function did not crash for a few models whereas `betaMPT` (JAGS) crashed. Moreover, the results are identical if both methods work. 

Therefore, I think it is reasonable to use `betaMPTcpp` as a default. Does anybody have other opinions or experiences, in which case `betaMPT` worked but `betaMPTcpp` did not?

**Comment by mariusbarth** [comment]
I didn't check `betaMPTcpp`, but the JAGS variant crashed sometimes.
Probably the most sensible solution would be to additionally implement the C++ version, keep the JAGS version as it is, and set only the C++ version as the default method.

**Comment by danheck** [comment]
`betaMPTcpp` now supported: https://github.com/mpt-network/MPTmultiverse/commit/af7e6cb0b35809ef2ea74297216b5963513d0059
